name: Тестирование статического HTML
on: [push]
jobs:
cypress-run:
runs-on: ubuntu-latest
defaults:
run:
working-directory: ./test
steps:
- name: Checkout
uses: actions/checkout@v4
- name: Установка Node.js
uses: actions/setup-node@v4
with:
node-version: 18
- name: Установка зависимостей
run: npm ci
- name: Установка http-server
run: npm install -g http-server
- name: Запуск сервера и тестов Cypress
uses: cypress-io/github-action@v6
with:
working-directory: ./test
start: npx http-server . --port 3000
wait-on: 'http://localhost:3000'